version: '3.4'
services:
  maDB:
    image: mariadb:latest
    environment:
      MARIADB_USER: "boring"
      MARIADB_PASSWORD: "OUKIL"
      MARIADB_ROOT_PASSWORD: "OUKIL"
    ports:
      - "3306:3306"
  glowof:
    build: .
    image: theboringway/glowof:back
    ports:
      - "5037:80"
    depends_on:
      - maDB
